project_id = "wytxdmxuhxfdpdqbcrea"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.og-article]
verify_jwt = false

[functions.sitemap]
verify_jwt = false
